export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';

export const POST_DATA_START = 'POST_DATA_START';
export const POST_DATA_SUCCESS = 'POST_DATA_SUCCESS';
export const POST_DATA_FAIL = 'POST_DATA_FAIL';

export const BOOK_DATA_START = 'BOOK_DATA_START';
export const BOOK_DATA_SUCCESS = 'BOOK_DATA_SUCCESS';
export const BOOK_DATA_FAIL = 'BOOK_DATA_FAIL';

export const FETCH_DATA_DETAILS = 'FETCH_DATA_DETAILS';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const STUDENT_LOGIN = 'STUDENT_LOGIN';
export const ADMIN_LOGIN = 'ADMIN_LOGIN';
